spring:
  application:
    name: atividade-1
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:h2:mem:atividade-1-db
    driver-class-name: org.h2.Driver
    username: luan
    password: 1234

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true